config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, path: :public, skip: [:passwords], controllers: {#skipオプションで不要なルーティングを削除
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :end_user do#guest_sign_in機能の際追加
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {#skipオプションで不要なルーティングを削除
    sessions: "admin/sessions"
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :admin do#guest_sign_in機能の際追加
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in'
  end

  root to: "homes#top"
  get "home/derivation"=>"homes#derivation", as: "derivation"
  get "home/outline"=>"homes#outline", as: "outline"

  namespace :public do
    get '/end_users/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
    patch '/end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    resources :spots do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "search" => "spots#search"
    resources :genres
    resources :end_users do#controllerでmy_pageを定義したからdo-endの間にget :my_page, on: :collectionを記述
      get :my_page, on: :collection
      get :favorites
    end
  end

  namespace :admin do
    resources :end_users
    resources :spots do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only: [:destroy]
    end
    get "search" => "spots#search"
    resources :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :spots, dependent: :destroy

  validates :name, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
	  @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_index.html.erb
<h2 class="mt-5">ジャンル一覧</h2>
<table class="table">
  <tbody>
    <% genres.each do |genre| %>
    <tr>
      <th><%= genre.name %></th>
      <th></th>
      <th></th>
      <th>
        <% unless ["施設", "自然"].include?(genre.name) %>
            <%= link_to '削除',  admin_genre_path(genre), method: :delete, class:'btn btn-danger btn-block' %>
        <% end %>
      </th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/_new.html.erb
<h2>ジャンル追加</h2>
<div class="row">

  <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <div class="col-auto" style="display:flex">
      <%= f.text_field :name, autofocus: true, placeholder:"新規ジャンルを入力 "%>
      <%= f.submit '新規登録',class:'btn btn-success ml-3' %>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-5 mt-5'>
      <%= render 'new', genre: @genre %>
    </div>

    <div class='col-md-4 offset-md-1'>
       <%= render 'index', genres: @genres %>
    </div>
  </div>
</div>