config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, path: :public, skip: [:passwords], controllers: {#skipオプションで不要なルーティングを削除
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :end_user do#guest_sign_in機能の際追加
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {#skipオプションで不要なルーティングを削除
    sessions: "admin/sessions"
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :admin do#guest_sign_in機能の際追加
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in'
  end

  root to: "homes#top"
  get "home/derivation"=>"homes#derivation", as: "derivation"
  get "home/outline"=>"homes#outline", as: "outline"

  namespace :public do
    get '/end_users/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
    patch '/end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    resources :spots do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "search" => "spots#search"
    resources :genres
    resources :end_users do#controllerでmy_pageを定義したからdo-endの間にget :my_page, on: :collectionを記述
      get :my_page, on: :collection
      get :favorites
    end
  end

  namespace :admin do
    resources :end_users
    resources :spots do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only: [:destroy]
    end
    get "search" => "spots#search"
    resources :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    has_many :spots, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    # has_many :favorited_spots, through: :favorites, source: :spot#いいね数ランキングで記述
    has_one_attached :profile_image

    validates :first_name, presence: true
    validates :last_name, presence: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_profile_image.png')
      profile_image.attach(io: File.open(file_path), filename: 'no_profile_image.png', content_type: 'image/png')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def name
    # self.first_name + ' ' + self.last_name と同義で#{}はRubyの式展開
    "#{self.last_name} #{self.first_name}"
  end

  def self.guest
    find_or_create_by!(email: 'test@com') do |end_user|#find_or_create_by!でゲストユーザーが無ければ作成、あれば取り出す
      end_user.password = SecureRandom.urlsafe_base64#↓ゲストユーザーがない時に作成するユーザー情報
      end_user.name = 'サンプル 太郎'
    end
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @end_users = EndUser.page(params[:page]).per(10)
  end

  def show
    @end_user = EndUser.find(params[:id])
    @spots = @end_user.spots

  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
   @end_user = EndUser.find(params[:id])
   @end_user.update(end_user_params)
   redirect_to admin_end_users_path
  end

 private

 def end_user_params
  params.require(:end_user).permit(:last_name, :first_name, :introduction, :profile_image, :is_deleted)
 end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/_index.html.erb
<h4><%= end_user.name %>&nbsp;&nbsp;さんの投稿</h4>
<table class="table">
  <thead>
    <tr>
      <th>場所の名前</th>
      <th>いいね数</th>
      <th>おすすめ度</th>

    </tr>
  </thead>
  <tbody>
    <% spots.each do |spot| %>
      <tr>
        <td><%= link_to spot.name, admin_spot_path(spot.id) %></td>
        <td><%= spot.favorites.count %> いいね</td>
        <td id="star-rate<%= spot.id %>"></td>
      </tr>

      <script>
        $('#star-rate<%= spot.id %>').empty();
        $('#star-rate<%= spot.id %>').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          readOnly: true,
          // readOnly: true,で表示のみになる
        score: <%= spot.star %>,
        scoreName: 'spot[star]',
          half: false,
        });
      </script>

    <% end %>
  </tbody>
</table>

app/views/admin/end_users/_profile.html.erb
<h2>会員情報</h2>

<%= image_tag end_user.get_profile_image(200,200) %>

<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>会員名</th>
      <th><%= end_user.name %></th><!--modelで疑似的にnameを定義しているため、nameが使用可能-->
    </tr>
    <tr>
      <th>自己紹介文</th>
      <th><%= end_user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="col-md-6 mb-5">
  <%= link_to "会員ステータス編集", edit_admin_end_user_path(@end_user), class: "btn btn-success" %>
</div>

app/views/admin/end_users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md mt-5">
      <h2><%= @end_user.name %>さんの会員ステータス編集画面</h2>
    </div>
  </div>

    <%= form_with model: @end_user, url: admin_end_user_path(@end_user), method: :patch do |f| %>

    <div class="row mt-5 mb-3">
      <div class="col-3"></div>
      <div class="col-md-2">
        <p><strong>会員ステータス</strong></p>
      </div>

      <div class="col-md-2">
        <%= f.radio_button :is_deleted, false, checked: true %>
        <strong style="color:#32cd32;"><%= f.label :is_deleted, "有効", value: false %></strong>
      </div>

      <div class="col-md-2">
        <%= f.radio_button :is_deleted, true %>
         <strong style="color:#dc143c;"><%= f.label :is_deleted, "退会", value: true %></strong>
      </div>
    </div>

    <div class="row mt-5 mb-3">
      <div class="col-md-6 text-right">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/end_users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto my-5">
      <h4>会員一覧</h4>

      <div class="row mt-3">
        <div class="col-md-10 mx-auto">
          <table class="table">
            <thead>
              <tr>
                <th class="text-center" style="width: 15% ">会員ID</th>
                <th class="text-center" style="width: 30%">会員名</th>
                <th class="text-center" style="width: 20%">ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @end_users.each do |end_user| %>
                <tr>
                  <td class="text-center"><%= end_user.id %></td>
                  <td class="text-center">
                    <%= link_to admin_end_user_path(end_user) do %>
                      <u class="text-dark"><%= end_user.last_name %><%= end_user.first_name %></u>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <% if end_user.is_deleted == false %>
                      <div class="text-success"><strong>有効</strong></div>
                    <% else %>
                      <div class="text-muted"><strong>退会</strong></div>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row my-2">
        <div class="col-md-5"></div>
          <%= paginate @end_users %>
      </div>

     </div>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row mt-5'>
    <div class='col-5 mt-2'>
      <%= render 'profile', end_user: @end_user %>
    </div>

    <div class='col-md-6 offset-md-1'>
       <%= render 'index', spots: @spots, end_user: @end_user %>
    </div>
  </div>
</div>