config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, path: :public, skip: [:passwords], controllers: {#skipオプションで不要なルーティングを削除
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :end_user do#guest_sign_in機能の際追加
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {#skipオプションで不要なルーティングを削除
    sessions: "admin/sessions"
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :admin do#guest_sign_in機能の際追加
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in'
  end

  root to: "homes#top"
  get "home/derivation"=>"homes#derivation", as: "derivation"
  get "home/outline"=>"homes#outline", as: "outline"

  namespace :public do
    get '/end_users/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
    patch '/end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    resources :spots do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "search" => "spots#search"
    resources :genres
    resources :end_users do#controllerでmy_pageを定義したからdo-endの間にget :my_page, on: :collectionを記述
      get :my_page, on: :collection
      get :favorites
    end
  end

  namespace :admin do
    resources :end_users
    resources :spots do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only: [:destroy]
    end
    get "search" => "spots#search"
    resources :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord

  belongs_to :prefecture
  belongs_to :genre
  belongs_to :end_user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :explanation, presence: true
  validates :address, presence: true
  validates :star, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'no_image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  scope :published, -> {where(is_published_flag: true)}# 公開・非公開機能
  scope :unpublished, -> {where(is_published_flag: false)}

  def favorited_by?(end_user)#favorited_by?メソッドでいいねを既に押しているか、押していないか判断
    favorites.exists?(end_user_id: end_user.id)
  end
end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @spots = Spot.page(params[:page])
  end

  def show
    @spot = Spot.find(params[:id])
    @end_user = @spot.end_user
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to admin_spots_path
  end

  def search
    query = Spot.all
    query = query.where(prefecture_id: params[:prefecture_id]) if params[:prefecture_id].present?
    query = query.where(genre_id: params[:genre_id]) if params[:genre_id].present?
    query = query.where("name LIKE ?", "%#{params[:name]}%") if params[:name].present?
    @spots = query.page(params[:page])
    render :index
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :prefecture_id, :genre_id)
  end

end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/views/admin/spots/_comment.html.erb
<div class ="row">
  <div class= "col-md-9"></div>
</div>

<div class ="row">
  <div class= "col-md-9">
    <p>コメント件数：<%= spot.comments.count %></p>
  </div>
</div>

<div class ="row">
<% spot.comments.each do |comment| %>
  <div class ="col-md-3">
    <%= image_tag comment.end_user.get_profile_image(100,100) %>
  </div>
  <div class ="col-md-4">
    <div style="font-size:13px"><%= comment.end_user.name %></div>
    <strong style="display:block">
      <%= link_to "削除", admin_spot_comment_path(comment.spot.id, comment.id), method: :delete ,style: "color:red;"%>
    </strong>
  </div>

  <div class ="col-md-5">
    <div class ="row">
      <div class ="col-md">
        <%= comment.created_at.strftime('%Y/%m/%d') %>
      </div>
    </div>
    <div class ="row">
      <div class ="col-md">
        <%= comment.comment %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/admin/spots/_favorites_show.html.erb
<div class ="row">
  <div class ="col-4">
    <p>いいね</p>
  </div>

  <div class ="col-4">
    <p>
      <%= spot.favorites.count %> いいね
    </p>
  </div>

</div>

app/views/admin/spots/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col text-center"><h2>会員投稿一覧</h2></div>

    <div class="search_form col-md-9 text-right">
      <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :name , placeholder:"🔍名称を入力" %>
        <%= f.select :prefecture_id, options_from_collection_for_select(Prefecture.all, :id, :name), { include_blank: '--都道府県--'}%>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), { include_blank: '--ジャンル--'} %>
        <!--options_from_collection_for_selectの記述でプルダウンにデータが入る-->
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
    </div>
    
  </div>
  
  <div class="row mt-2">
    <%  @spots.each do |spot| %>
       <div class="spot_index col-md-3 p-2 text-center">
        <%= link_to admin_spot_path(spot) do %>
          <%= image_tag spot.get_image(200, 200) %><br>
          <%= spot.name %>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        いいね数 <%= spot.favorites.count %>
      </div>
    <% end %>
  </div>

  <div class="row my-md-2">
    <div class="col-md-5"></div>
    <div class="col-md-3">
      <%= paginate @spots %>
    </div>
  </div>
  
</div>

app/views/admin/spots/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-2">
      <h2>投稿詳細</h2>
    </div>

    <div class="col-md-7"></div>

    <div class="col-md-1">
      <%= link_to admin_spots_path do %>
        <button type="button" class=" btn-circle-flat  btn-circle">🔙</button>
      <% end %>
    </div>

    <% if @spot.end_user == current_admin.id %>
      <div class="col-md-1">
        <%= link_to edit_public_spot_path(@spot.id) do %>
          <button type="button" class=" btn-circle-flat  btn-circle">✎</button>
        <% end %>
      </div>
    <% end %>

      <div class="col-md-1">
        <%= link_to admin_spot_path(@spot.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
          <button type="button" class=" btn-circle-flat  btn-circle">×</button>
        <% end %>
      </div>

  </div>

  <div class="row mt-3 mb-4">
    <div class="col-md-6">
      <%= image_tag @spot.get_image(500, 500), class: 'img-fluid' %>
    </div>

    <div class="col-md-5">

      <div class ="row">
        <div class ="col-4">
          <p>名称</p>
        </div>
        <div class ="col-8">
          <%= @spot.name %>
        </div>
      </div>

      <div class ="row">
        <div class ="col-4">
          <p>場所の説明文</p>
        </div>
        <div class ="col-8">
          <%= @spot.explanation %>
        </div>
      </div>

      <div class ="row">
        <div class ="col-4">
          <p>都道府県</p>
         </div>
        <div class ="col-8">
          <%= @spot.prefecture.name %>
        </div>
      </div>

      <div class ="row">
        <div class ="col-4">
          <p>所在地</p>
        </div>
        <div class ="col-8">
          <%= @spot.address %>
        </div>
      </div>

      <div class ="row">
        <div class ="col-4">
          <p>ジャンル</p>
        </div>
        <div class ="col-8">
          <%= @spot.genre.name %>
        </div>
      </div>

      <div class ="row">
        <div class ="col-4">
          <p>おすすめ度</p>
        </div>
        <div class ="col-8">
          <%= render 'public/spots/star_result', spot: @spot %>
        </div>
      </div>

      <div class="favorite_btn">
       <%= render 'favorites_show', spot: @spot %>
      </div>

      <div class ="row">
        <div class ="col-4">
          <p>投稿者名</p>
         </div>
        <div class ="col-8">
            <%= link_to admin_end_user_path(@end_user) do %>
              <%= image_tag @spot.end_user.get_profile_image(100, 100) %>
              <%= @spot.end_user.name %>
            <% end %>
        </div>
      </div>
      <%= render 'comment', spot: @spot, comment: @comment %>

    </div>
  </div>
 </div>