config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, path: :public, skip: [:passwords], controllers: {#skipオプションで不要なルーティングを削除
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :end_user do#guest_sign_in機能の際追加
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {#skipオプションで不要なルーティングを削除
    sessions: "admin/sessions"
  }#生成したコントローラーがどこに存在するかを記述

  devise_scope :admin do#guest_sign_in機能の際追加
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in'
  end

  root to: "homes#top"
  get "home/derivation"=>"homes#derivation", as: "derivation"
  get "home/outline"=>"homes#outline", as: "outline"

  namespace :public do
    get '/end_users/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
    patch '/end_users/withdraw' => 'end_users#withdraw', as: 'withdraw'
    resources :spots do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "search" => "spots#search"
    resources :genres
    resources :end_users do#controllerでmy_pageを定義したからdo-endの間にget :my_page, on: :collectionを記述
      get :my_page, on: :collection
      get :favorites
    end
  end

  namespace :admin do
    resources :end_users
    resources :spots do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only: [:destroy]
    end
    get "search" => "spots#search"
    resources :genres
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'admin.test@com') do |admin|#find_or_create_by!でゲストユーザーが無ければ作成、あれば取り出す
      admin.password = SecureRandom.urlsafe_base64#↓ゲストユーザーがない時に作成するユーザー情報
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :end_user
  belongs_to :spot

  validates :comment, length: {maximum: 30}

end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    has_many :spots, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    # has_many :favorited_spots, through: :favorites, source: :spot#いいね数ランキングで記述
    has_one_attached :profile_image

    validates :first_name, presence: true
    validates :last_name, presence: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_profile_image.png')
      profile_image.attach(io: File.open(file_path), filename: 'no_profile_image.png', content_type: 'image/png')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def name
    # self.first_name + ' ' + self.last_name と同義で#{}はRubyの式展開
    "#{self.last_name} #{self.first_name}"
  end

  def self.guest
    find_or_create_by!(email: 'test@com') do |end_user|#find_or_create_by!でゲストユーザーが無ければ作成、あれば取り出す
      end_user.password = SecureRandom.urlsafe_base64#↓ゲストユーザーがない時に作成するユーザー情報
      end_user.name = 'サンプル 太郎'
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
belongs_to :end_user
belongs_to :spot

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :spots, dependent: :destroy

  validates :name, presence: true

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  has_many :spots, dependent: :destroy

end

app/models/spot.rb
class Spot < ApplicationRecord

  belongs_to :prefecture
  belongs_to :genre
  belongs_to :end_user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :explanation, presence: true
  validates :address, presence: true
  validates :star, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'no_image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  scope :published, -> {where(is_published_flag: true)}# 公開・非公開機能
  scope :unpublished, -> {where(is_published_flag: false)}

  def favorited_by?(end_user)#favorited_by?メソッドでいいねを既に押しているか、押していないか判断
    favorites.exists?(end_user_id: end_user.id)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController


  def destroy
    spot = Spot.find(params[:spot_id])
    Comment.find_by(id: params[:id],spot_id: params[:spot_id]).destroy
    redirect_to admin_spot_path(spot)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
	  @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @spots = Spot.page(params[:page])
  end

  def show
    @spot = Spot.find(params[:id])
    @end_user = @spot.end_user
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to admin_spots_path
  end

  def search
    query = Spot.all
    query = query.where(prefecture_id: params[:prefecture_id]) if params[:prefecture_id].present?
    query = query.where(genre_id: params[:genre_id]) if params[:genre_id].present?
    query = query.where("name LIKE ?", "%#{params[:name]}%") if params[:name].present?
    @spots = query.page(params[:page])
    render :index
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :prefecture_id, :genre_id)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :email])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    spot_ranking_ids = Favorite.select('spot_id, count(id) as count').group('spot_id').order('count
 DESC').limit(5).map {|favorite| favorite.spot_id}
    @spots = Spot.find(spot_ranking_ids)

  end

  def derivation
  end

  def outline
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--余分なルーティングを削除したため、「Forgot your password?」の部分でリンク先が存在しない
というエラーが発生するため、上記から下を削除した-->

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col" >

        <div class="row mt-4"></div>
        <div class="footer_menu">
          <% if end_user_signed_in? %>

            <%= link_to derivation_path ,class: 'text-light' do %>
              <strong>サイト由来</strong>
            <% end %>

            &nbsp;&nbsp;&nbsp;&nbsp;

            <%= link_to outline_path ,class: 'text-light' do %>
              <strong>サイト概要<strong>
            <% end %>

             &nbsp;&nbsp;&nbsp;&nbsp;

            <%= link_to destroy_end_user_session_path, method: :delete,class: 'text-light' do %>
              <strong>ログアウト</strong>
            <% end %>

          <% elsif admin_signed_in? %>

            <%= link_to derivation_path ,class: 'text-light' do %>
              <strong>サイト由来</strong>
            <% end %>

            &nbsp;&nbsp;&nbsp;&nbsp;

            <%= link_to outline_path ,class: 'text-light' do %>
              <strong>サイト概要<strong>
            <% end %>

             &nbsp;&nbsp;&nbsp;&nbsp;

            <%= link_to  destroy_admin_session_path, method: :delete,class: 'text-light' do %>
              <strong>ログアウト</strong>
            <% end %>

          <% else %>

            <%= link_to derivation_path ,class: 'text-light' do %>
              <strong>サイト由来</strong>
            <% end %>

            &nbsp;&nbsp;&nbsp;&nbsp;

            <%= link_to outline_path ,class: 'text-light' do %>
              <strong>サイト概要</strong>
            <% end %>

            <%= link_to new_admin_session_path ,class: 'admin_signed_in_command text-right' do %>
              <p>◆</p>
            <% end %>

          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light mb-2">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag 'logo.png',size:150, class: 'logo' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <% if end_user_signed_in? %>

            <li>
              <%= link_to my_page_public_end_users_path ,class: 'nav-link text-light' do %>
               <div class="nav-btn"><strong>マイページ</strong></div>
              <% end %>
            </li>

            <li>
              <%= link_to  new_public_spot_path ,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>投稿する</strong></div>
              <% end %>
            </li>

            <li>
              <%= link_to  public_spots_path ,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>みんなの投稿一覧</strong></div>
              <% end %>
            </li>

          <% elsif admin_signed_in? %>
            <li>
              <%=  link_to admin_end_users_path ,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>会員一覧</strong></div>
              <% end %>
            </li>

            <li>
              <%=  link_to admin_genres_path,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>ジャンル一覧</strong></div>
              <% end %>
            </li>

            <li>
              <%= link_to admin_spots_path ,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>会員投稿一覧</strong></div>
              <% end %>
            </li>

          <% else %>

            <li>
              <%= link_to new_end_user_session_path ,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>ログイン</strong></div>
              <% end %>
            </li>

            <li>
              <%= link_to new_end_user_registration_path ,class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>新規会員登録</strong></div>
              <% end %>
            </li>

            <li>
              <%= link_to end_users_guest_sign_in_path , method: :post, class: 'nav-link text-light' do %>
                <div class="nav-btn"><strong>ゲストログイン</strong></div>
              <% end %>
            </li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tripple</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %><!--BootStrap導入の際記述変更-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--stylesheet_pack_tagはJavaScript/packsのを読み込み、 stylesheet_link_tagはassetsの方を読み込む。-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/skipper-slider@1.2.1/dist/skippr.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/skipper-slider@1.2.1/dist/skippr.css">
  </head>

  <body>
    <header><%= render 'layouts/header' %></header>
    <main><%= yield %></main>
    <footer><%= render 'layouts/footer' %></footer>
  </body>
</html>